import { mkdir } from 'node:fs/promises';
import { expect, test } from '@playwright/test';

const fixture = 'http://127.0.0.1:3198';
const artifacts = '/tmp/cubic-alpha11-slice7-3';
const generic = 'If an eligible account exists, password reset instructions have been sent.';

test.beforeEach(async ({ page, request }) => {
  await request.post(`${fixture}/__test/reset`);
  await page.goto('/login');
});

test('verified-account recovery is generic, fragment-safe, and signs out old sessions', async ({ page, request }, testInfo) => {
  await mkdir(artifacts, { recursive: true });
  await request.get(`${fixture}/__test/email-verified?value=true`);
  const project = testInfo.project.name;
  const forgot = page.getByRole('link', { name: 'Forgot password?' });
  await expect(forgot).toBeVisible();
  await forgot.focus();
  await page.keyboard.press('Enter');
  await expect(page.getByRole('heading', { name: 'Reset your password.' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  if (project === 'desktop' || project === 'phone-portrait') await page.goto('/login').then(async () => {
    await expect(forgot).toBeVisible();
    await page.screenshot({ path: `${artifacts}/${project === 'desktop' ? 'desktop' : 'phone'}-login-forgot-password.png` });
    await forgot.click();
  });
  if (project === 'desktop' || project === 'phone-portrait') await page.screenshot({ path: `${artifacts}/${project === 'desktop' ? 'desktop' : 'phone'}-forgot-password.png` });
  const unrelated = await request.get('/api/v1/auth/me', { headers: { cookie: 'cubic_session=browser-peer' } });
  expect(unrelated.status()).toBe(200);
  await page.getByLabel('Email or username').fill('tester@example.test');
  if (project.includes('phone')) expect((await page.getByRole('button', { name: 'Send reset instructions' }).boundingBox())!.height).toBeGreaterThanOrEqual(44);
  await page.getByRole('button', { name: 'Send reset instructions' }).click();
  await expect(page.getByRole('status')).toContainText(generic);
  if (project === 'desktop') await page.screenshot({ path: `${artifacts}/desktop-recovery-sent.png` });
  await page.goto('/forgot-password');
  await page.getByLabel('Email or username').fill('tester');
  await page.getByRole('button', { name: 'Send reset instructions' }).click();
  await expect(page.getByRole('status')).toContainText(generic);
  await page.goto('/forgot-password');
  await page.getByLabel('Email or username').fill('missing-account');
  await page.getByRole('button', { name: 'Send reset instructions' }).click();
  await expect(page.getByRole('status')).toHaveText(generic);
  const mail = (await (await request.get(`${fixture}/__test/mail`)).json()).messages;
  expect(mail).toHaveLength(2);
  expect(mail.at(-1).url).toContain('/reset-password#token=');
  expect((await request.get('/api/v1/auth/me', { headers: { cookie: 'cubic_session=browser-peer' } })).status()).toBe(200);
  await page.goto(mail.at(-1).url);
  await expect(page.getByRole('heading', { name: 'Choose a new password.' })).toBeVisible();
  expect(page.url()).not.toContain('#');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  const storage = await page.evaluate(() => ({ local: Object.entries(localStorage), session: Object.entries(sessionStorage) }));
  expect(storage.local).toEqual([]);
  expect(storage.session.map(([key]) => key).sort()).toEqual(['sveltekit:scroll', 'sveltekit:snapshot']);
  expect(JSON.stringify(storage)).not.toContain(mail.at(-1).url.split('#token=')[1]);
  const shot = project === 'desktop' ? 'desktop-reset-password.png' : project === 'phone-portrait' ? 'phone-reset-password.png' : project === 'phone-landscape' ? 'phone-landscape-reset-password.png' : project === 'small-phone' ? 'small-phone-reset-password.png' : null;
  if (shot) await page.screenshot({ path: `${artifacts}/${shot}` });
  if (project.includes('phone')) expect((await page.getByRole('button', { name: 'Reset password' }).boundingBox())!.height).toBeGreaterThanOrEqual(44);
  const newPassword = page.getByLabel('New password', { exact: true });
  const confirmation = page.getByLabel('Confirm new password', { exact: true });
  await newPassword.fill('test-only-new-password');
  await confirmation.fill('test-only-mismatch');
  let submitted = 0;
  page.on('request', (sent) => { if (sent.url().endsWith('/api/v1/auth/password/reset')) submitted += 1; });
  await page.getByRole('button', { name: 'Reset password' }).click();
  await expect(page.getByRole('alert')).toContainText('New passwords do not match.');
  expect(submitted).toBe(0);
  await confirmation.fill('test-only-new-password');
  await page.getByRole('button', { name: 'Reset password' }).click();
  await expect(page.getByRole('heading', { name: 'Password changed.' })).toBeVisible();
  await expect(page.getByText('All previous sessions were signed out.')).toBeVisible();
  expect(submitted).toBe(1);
  if (project === 'desktop' || project === 'phone-portrait') await page.screenshot({ path: `${artifacts}/${project === 'desktop' ? 'desktop' : 'phone'}-reset-success.png` });
  expect((await request.get('/api/v1/auth/me', { headers: { cookie: 'cubic_session=browser-fixture' } })).status()).toBe(401);
  expect((await request.post('/api/v1/auth/login', { data: { identifier: 'tester', password: 'test-only-password' } })).status()).toBe(401);
  await page.getByRole('link', { name: 'Sign in to Cubic' }).click();
  await page.getByLabel('E-mail or username').fill('tester');
  await page.getByLabel('Password').fill('test-only-new-password');
  await page.getByRole('button', { name: 'Log in' }).click();
  await expect(page).toHaveURL(/\/app$/);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  const mailCountBeforeUnverified = (await (await request.get(`${fixture}/__test/mail`)).json()).messages.length;
  await request.get(`${fixture}/__test/email-verified?value=false`);
  await page.goto('/forgot-password');
  await page.getByLabel('Email or username').fill('tester');
  await page.getByRole('button', { name: 'Send reset instructions' }).click();
  await expect(page.getByRole('status')).toHaveText(generic);
  expect((await (await request.get(`${fixture}/__test/mail`)).json()).messages).toHaveLength(mailCountBeforeUnverified);
});

test('disabled mail hides the login action and direct recovery page has no form', async ({ page, request }, testInfo) => {
  await request.get(`${fixture}/__test/mail-mode?value=disabled`);
  await page.reload();
  await expect(page.getByRole('link', { name: 'Forgot password?' })).toHaveCount(0);
  if (testInfo.project.name === 'desktop') await page.screenshot({ path: `${artifacts}/desktop-recovery-disabled.png` });
  await page.goto('/forgot-password');
  await expect(page.getByText('Password recovery is unavailable on this Cubic instance.')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Send reset instructions' })).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
